### ISSUE TITLE
Allow pandoc (fenced|inline)_code_attributes to set minted options

### ISSUE THREAD

**Issue by jpcirrus** [nick-ulle/pandoc-minted#1]
It would be useful to be able to set any desired minted options from the respective pandoc `fenced_code_attributes`and `inline_code_attributes` similar to [this](https://gist.github.com/jepio/3ecaa6bba2a53ff74f2e)

**Comment by nick-ulle** [comment]
I agree. I'll look into it this weekend.

**Comment by paulsmirnov** [comment]
Found similar attempt: https://gist.github.com/jepio/3ecaa6bba2a53ff74f2e
