### ISSUE TITLE
Package minted Error: Missing Pygments output

### ISSUE THREAD

**Issue by iphilgood** [nick-ulle/pandoc-minted#2]
Hi @nick-ulle 

I'm currently trying to use your script in my thesis. I've installed Python. I've also installed `pandocfilters` via pip.

``` shell
pandoc --no-highlight --filter ./minted.py "$(INPUTDIR)"/*.md \
  -o "$(OUTPUTDIR)/thesis.pdf" \
  -H "$(STYLEDIR)/preamble.tex" \
  --template="$(STYLEDIR)/template.tex" \
  --bibliography="$(BIBFILE)" 2>pandoc.log \
  --csl="$(STYLEDIR)/ref_format.csl" \
  -V fontsize=12pt \
  -V papersize=a4paper \
  -V documentclass:report \
  -N \
  --latex-engine-opt='-shell-escape' \
  --latex-engine=xelatex \
  --verbose
```

I'm always getting the following error:

```
! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.
```

In addition to the error message above I have the following in my log file of pandoc:

```
Error: cannot read infile: [Errno 2] No such file or directory: 'input.pyg'
system returned with code 256
```

Do you have any idea why this is happening?

Thanks for your help
Phil

**Comment by nick-ulle** [comment]
Pandoc-minted doesn't handle any files directly, only the data structure passed to it by pandoc, so I suspect the error is coming from minted.

Have you verified that minted is working on your machine for ordinary LaTeX files?

**Comment by iphilgood** [comment]
Yeah, that's the thing. I made it work in a single file. But as soon as I try to compile my files with pandoc it just doesn't seem to work.

Here's my setup which works

``` latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{swift}
let answer = "forty-two"
for i in 1 ... 8 {
  moveForward()
  if isOnClosedSwitch && isBlocked {
    toggleSwitch()
    turnLeft()
    moveForward()
  }
}
\end{minted}
\end{document}
```

When I run it with `xelatex -shell-escape foo.tex` everything works like a charm.

Do you need any additional information for troubleshooting, just let me know. I really appreciate your work 😊

**Comment by jpcirrus** [comment]
You can't use the shell-escape LaTeX option when creating a PDF directly with pandoc. I ran into the same issue and can't remember where I read that. Try it without any filters and you'll get the same issue.

**Comment by nick-ulle** [comment]
Thanks! I ran into the shell-escape problem a long time ago, but didn't think to connect it to this.

Here's a work around: have Pandoc generate a LaTeX file and then use a standard LaTeX compiler to generate the PDF. My workflow is to call pandoc and then latexmk from a makefile.

**Comment by iphilgood** [comment]
Alright, I see! Thank you @jpcirrus and @nick-ulle. I'll definitely check your approach out.

Thanks for your help.

**Comment by gandalfsaxe** [comment]
Hi guys,

I've also run into this problem. Does the problem seem to be with `minted` or `pandoc`? I thought I'd just make an issue of this at the relevant repo. Would be so nice if pandoc could handle the PDF conversion instead having to do it in a two-step pandoc-pdflatex process :)

**Comment by nick-ulle** [comment]
For anyone else having this problem, see [this issue on the Pandoc issue tracker](https://github.com/jgm/pandoc/issues/4721).
