### ISSUE TITLE
Permission denied on windows

### ISSUE THREAD

**Issue by usfkotb** [nick-ulle/pandoc-minted#3]
```
pandoc.exe: Error running filter ./pandoc-minted.py
terminateProcess: permission denied (Permission denied)
```
The pandoc-minted.py file is given permission to excute

**Comment by nanodeath** [comment]
Somewhat relatedly, if you follow the directions and put the script on your PATH, you always get this:

```
pandoc: Error running filter pandoc-minted.py
pandoc-minted\pandoc-minted.py: createProcess: invalid argument (Exec format error)
```

You *have* to specify the full path, using **forward** slashes, on Windows for it to work well enough to get the permission denied error. Seems to be documented [here](https://github.com/jgm/pandoc/issues/1096).

**Comment by nick-ulle** [comment]
Closing as this seems to be an issue with Pandoc rather than an issue specific to this filter.
