### ISSUE TITLE
Mac: error when running ln command

### ISSUE THREAD

**Issue by gandalfsaxe** [nick-ulle/pandoc-minted#4]
Running the command from `README.md` as such: `ln -rs pandoc-minted.py DIRECTORY/pandoc-minted` (with a real path directory in place of DIRECTORY), I get:

```bash
ln: illegal option -- r
usage: ln [-Ffhinsv] source_file [target_file]
       ln [-Ffhinsv] source_file ... target_dir
       link source_file target_file
```

Looking at the man page for `ln`, it seems like there is no `-r` option for `ln`, at least on Mac. Perhaps this should be correctly, or in the case it's valid on linux, made separate for Mac.

**Comment by gandalfsaxe** [comment]
And actually, this also made a non-working symbolic link:

```bash
ln -s pandoc-minted.py DIRECTORY/pandoc-minted
```

Instead it only worked if I used the full path on both paths

```bash
ln -s [FULL-PATH]/pandoc-minted.py [FULL-PATH]
```

Will be making a pull request with these fixes.

**Comment by nick-ulle** [comment]
You are likely running the `ln` command from a different directory than where you cloned `pandoc-minted.py`.

But thanks for pointing out that `-r` is not supported on OS X.
