### ISSUE TITLE
Even when in path: "Could not find executable pandoc-minted"

### ISSUE THREAD

**Issue by gandalfsaxe** [nick-ulle/pandoc-minted#5]
When I run `pandoc --filter pandoc-minted test.md -o test.pdf` I ge the error:

```bash
Error running filter pandoc-minted:
Could not find executable pandoc-minted
```

I have checked `echo $PATH` and I'm sure that the python script is in the path. Any ideas?

**Comment by gandalfsaxe** [comment]
Figured it out. I had to run it with filter `pandoc-minted.py`, i.e.:

```bash
pandoc --filter pandoc-minted.py test.md -o test.pdf
```

This should be fixed in the readme. Will be making a pull request with these fixes.

**Comment by nick-ulle** [comment]
Likely the symlink was not created correctly. The symlink should be called `pandoc-minted`, and if that's on the path (rather than `pandoc-minted.py`) then the filter should work.
