### ISSUE TITLE
Fails to build pdf

### ISSUE THREAD

**Issue by hasufell** [nick-ulle/pandoc-minted#7]
```
Error producing PDF.
! LaTeX Error: Environment minted undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.140 \begin{minted}
```

**Comment by DCsunset** [comment]
Same issue here.
Adding `\usepackage{minted}` in yaml header doesn't help as well.

**Comment by nick-ulle** [comment]
Make sure the [template file](https://pandoc.org/MANUAL.html#templates) you're using with Pandoc includes `\usepackage{minted}`.

This filter doesn't and can't set up the template file for you.
